### ISSUE TITLE
Production error when making PDF

### ISSUE THREAD

**Issue by BryceStevenWilley** [nonprofittechy/docassemble-MAHousingTRO#25]
Happens when images are added to PDFs in DA core code, from what I can see, the only time that should be is with the signature, but idk how could be breaking. Needs more looking into.

```
Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 8124, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8699, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8486, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9324, in askfor
    question_result = self.askfor(newMissingVariable, user_dict, old_user_dict, interview_status, variable_stack=variable_stack, questions_tried=questions_tried, seeking=seeking, follow_mc=follow_mc, recursion_depth=recursion_depth, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9165, in askfor
    question.processed_attachments(user_dict, seeking_var=origMissingVariable, use_cache=False)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 6507, in processed_attachments
    result_list.append(self.finalize_attachment(item[0], item[1], the_user_dict))
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 6717, in finalize_attachment
    the_pdf_file = docassemble.base.pdftk.fill_template(attachment['options']['pdf_template_file'].path(the_user_dict=the_user_dict), data_strings=result['data_strings'], images=result['images'], editable=result['editable'], pdfa=result['convert_to_pdf_a'], password=result['password'], template_password=result['template_password'], default_export_value=default_export_value)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/pdftk.py", line 346, in fill_template
    overlay_pdf_file.write(img2pdf.convert(output.getvalue()))
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/img2pdf.py", line 2400, in convert
    pdf.add_imagepage(
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/img2pdf.py", line 992, in add_imagepage
    page = self.writer.add_blank_page(page_size=(pagewidth, pageheight))
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/pikepdf/_methods.py", line 388, in add_blank_page
    raise ValueError('Page size must be between 3 and 14400 PDF units')
ValueError: Page size must be between 3 and 14400 PDF units
```

**Comment by samglover** [comment]
Since we're refactoring/updating this repo, this issue should no longer be an issue. We'll test PDF assembly as a matter of course while developing the new version.
